### ISSUE TITLE
Error while starting the bot

### ISSUE THREAD

**Issue by JaedonLau** [nates/ward#20]
 node index.js
[Discord] › ℹ  info      Logging in...
internal/fs/utils.js:269
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'private.pem'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at Object.main [as run] (/home/runner/ward/server.js:56:21)
    at Object.<anonymous> (/home/runner/ward/index.js:5:11)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'private.pem'
}
exit status 1

this is logged in the console

**Comment by waki285** [comment]
Try setting https in config.json to false

**Comment by JaedonLau** [comment]
i also don't know what to put in the secret key andpublic key

**Comment by JaedonLau** [comment]
> i also don't know what to put in the secret key and public key

**Comment by nates** [comment]
> 
> 
> > i also don't know what to put in the secret key and public key

You must use an SSL certificate.
